name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java (required for Android/Gradle)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3" # Use your project’s version

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Analyze code
      - name: Run flutter analyze
        run: flutter analyze

      # 6. Run tests
      - name: Run tests
        run: flutter test

      # 7. Accept Android licenses
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      # 8. Build Android APK
      - name: Build APK
        run: flutter build apk --debug


        # 9. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
