name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Install dependencies
        run: flutter pub get

      # Run analyzer but don’t fail build on warnings
      - name: Run flutter analyze
        run: flutter analyze || true

      - name: Run tests
        run: flutter test || true   # same here if you want APK even with failing tests

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
